/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class start */

#ifndef _Included_start
#define _Included_start
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     start
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_start_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     start
 * Method:    sumIntegers
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_start_sumIntegers
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     start
 * Method:    sayHelloToMe
 * Signature: (Ljava/lang/String;Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_start_sayHelloToMe
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     start
 * Method:    hashHeader
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_start_hashHeader
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
